### ISSUE TITLE
Regex to recognize templates is not supported by Firefox

### ISSUE THREAD

**Issue by pex81** [Savjee/button-text-card#10]
hi i'm trying to use this card, but i get this error

```
Custom element doesn't exist: button-text-card.

type: 'custom:button-text-card'
title: Only title
icon: 'mdi:format-title'
```

home-assistant.log
```
2020-03-19 16:33:17 ERROR (MainThread) [frontend.js.latest.202002205] https://192.168.1.33:8123/hacsfiles/button-text-card/button-text-card.js:271:96 SyntaxError: invalid regular expression flag s
2020-03-19 16:33:18 ERROR (MainThread) [frontend.js.latest.202002205] https://192.168.1.33:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:2696:228 TypeError: e.parentElement is null
2020-03-19 16:33:18 ERROR (MainThread) [frontend.js.latest.202002205] https://192.168.1.33:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:2696:228 TypeError: e.parentElement is null
```

resources.yaml
```
# Button Text Card
  - url: /hacsfiles/button-text-card/button-text-card.js
    type: module
```

**Comment by Savjee** [comment]
Which browser are you using and what version of HA are you running?

**Comment by pex81** [comment]
> 
> 
> Which browser are you using and what version of HA are you running?

I'm using Firefox
HA 106.6

**Comment by Savjee** [comment]
Thanks for reporting this!

It's related to the regex that I use to detect JS templates.
https://github.com/Savjee/button-text-card/blob/master/src/button-text-card.ts#L31

I will try to fix it tonight or tomorrow ;)

**Comment by pex81** [comment]
> 
> 
> Thanks for reporting this!
> 
> It's related to the regex that I use to detect JS templates.
> https://github.com/Savjee/button-text-card/blob/master/src/button-text-card.ts#L31
> 
> I will try to fix it tonight or tomorrow ;)

ok, I also tried with chrome, I will wait for the new version, thanks

**Comment by Savjee** [comment]
It should work fine on Chrome. Do you have the same issue there?

**Comment by pex81** [comment]
> It should work fine on Chrome. Do you have the same issue there?

On chrome I don't see the error but I don't see the card.

**Comment by Savjee** [comment]
Ah, that's an oversight on my part! Try defining an `entity` on the card. Then it will appear.

I'm working on fixing that right now. Stay tuned for a build in a few minutes. 

Ref #11

**Comment by pex81** [comment]
> 
> 
> Ah, that's an oversight on my part! Try defining an `entity` on the card. Then it will appear.
> 
> I'm working on fixing that right now. Stay tuned for a build in a few minutes.
> 
> Ref #11

On Chrome with entity it's ok
On Firefox with entity that same error.

**Comment by Savjee** [comment]
Can you try to install the latest version? I think it should be fixed now.

**Comment by pex81** [comment]
> 
> 
> Can you try to install the latest version? I think it should be fixed now.

I have update:
on firefox that same not work
home-assistant.log
`2020-03-19 17:41:54 ERROR (MainThread) [frontend.js.latest.202002205] https://192.168.1.33:8123/hacsfiles/button-text-card/button-text-card.js:3318:33 SyntaxError: invalid regular expression flag s`

**Comment by Savjee** [comment]
Did you reinstall the plugin and clear your cache?

The `s` flag was removed from the regex, so you shouldn't be seeing this error anymore.

**Comment by pex81** [comment]
> 
> 
> Did you reinstall the plugin and clear your cache?
> 
> The `s` flag was removed from the regex, so you shouldn't be seeing this error anymore.

Now work! Thank
But it always takes entity?

**Comment by Savjee** [comment]
Nope, entity isn't required anymore.

**Comment by pex81** [comment]
> 
> 
> Nope, entity isn't required anymore.

Ok thanks, 
is it possible to customize the style?

**Comment by Savjee** [comment]
Yes, you can change background and font color. Check the README ;)
