### ISSUE TITLE
Allow custom shadow color (with templating support)

### ISSUE THREAD

**Issue by Savjee** [Savjee/button-text-card#15]
Feedback by [fitim](https://community.home-assistant.io/t/lovelace-soft-ui-simple-and-clean-lovelace-configuration/159357/77?u=savjee)

It seems fair, as there is already the option to customize font & background color.

**Comment by ttaidapos** [comment]
Yes!  See below card with my theme, the shadow doesn't look nearly as nice compared to a "stock" hass theme.

![image](https://user-images.githubusercontent.com/27898709/80438708-6b1c2780-88ca-11ea-9853-901f3b44da17.png)

**Comment by ttaidapos** [comment]
Any update on this one?

**Comment by kenstone** [comment]
@ttaidapos This is looks like the default behavior if `ha-card-box-shadow` is not set in your theme. It really shows up in this manner when you've got a dark theme like this. Mine looked the same when I used the `slate` theme.

For example, in my theme, I have it set to a version that I'm interested in.

```yaml
  ha-card-box-shadow: '-5px -5px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15)'
```

**Comment by ttaidapos** [comment]
> @ttaidapos This is looks like the default behavior if `ha-card-box-shadow` is not set in your theme. It really shows up in this manner when you've got a dark theme like this. Mine looked the same when I used the `slate` theme.
> 
> For example, in my theme, I have it set to a version that I'm interested in.
> 
> ```yaml
>   ha-card-box-shadow: '-5px -5px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15)'
> ```

cool so i just add this line to my theme.  I presume if I set all to '0' it will remove the shadow completely?

**Comment by kenstone** [comment]
Yep.  Well, if you want no shadow, you should be able to set to

`ha-card-box-shadow: 'none'`

**Comment by ttaidapos** [comment]
> Yep. Well, if you want no shadow, you should be able to set to
> 
> `ha-card-box-shadow: 'none'`

This is awesome!!! worked perfectly.

**Comment by Savjee** [comment]
This should be fixed in the latest version.

Previous version:
![Screen Shot 2020-06-22 at 11 38 42](https://user-images.githubusercontent.com/817109/85272900-184f8e00-b47d-11ea-9e61-d4fb628d8ab9.png)

New version (follow the theme's background color and shadow color): 
![Screen Shot 2020-06-22 at 11 39 31](https://user-images.githubusercontent.com/817109/85272904-18e82480-b47d-11ea-8fa6-b8c7dd5aeb52.png)

**Comment by ttaidapos** [comment]
AMAZING!  Thank you!!!
