### ISSUE TITLE
Animate icons

### ISSUE THREAD

**Issue by renjithstalin** [Savjee/button-text-card#17]
Thanks for the wonderful plugin, have been using it in all my dashboards now.
Just wondering if it is possible to animate the icons? I tried 'spin: true' but not luck.

Thanks in advance,

**Comment by Savjee** [comment]
That's not yet possible but I'm willing to add that feature.
Could you point me to a plugin that does something similar? Then I can take a look at their CSS code ;)

**Comment by renjithstalin** [comment]
Thanks for the response, ' 'custom:button-card' has got spin element
https://github.com/custom-cards/button-card
example of the card that I am using:
state:
  - color: yellow
    spin: true
    value: CHARGING
  - color: green
    spin: true
    value: FINISHED_FULLY_CHARGED

**Comment by Savjee** [comment]
I created an `icon_animation` option that you can set to `spin`. I'll try to add more animations in the future, like pulsate ;)

**Comment by renjithstalin** [comment]
Thank you so very much!! my dashboards are of this card :D :D

**Comment by Savjee** [comment]
Hehe, same for me ;)
