### ISSUE TITLE
icon_color template rendering

### ISSUE THREAD

**Issue by kenstone** [Savjee/button-text-card#21]
I've tried to set the color of an icon by using the following:

```
icon_color: '[[[ return ''#FF0000'' ]]]'
```
This template works on the `title` field, but here on the `icon_color`, it displays the default color. If I hard code it (e.g. `icon_color: '#FF0000'`), it shows the color as expected.

As for a fix, my thought is that adding the following line to `_configureIconColor()` (before the default fall through option) will allow whatever is rendered to pass through. Haven't tested it yet, though.

```
   if (this._renderedConfig?.icon_color) {
      this.style.setProperty('--icon-color', this._renderedConfig.icon_color);
      return;
    }
```

**Comment by kenstone** [comment]
Finally able to test. No. that line doesn't fix.

**Comment by kenstone** [comment]
My fix was much simpler. Template rendering wasn't on for this property.

**Comment by Savjee** [comment]
Fixed by your PR: https://github.com/Savjee/button-text-card/pull/25

Thanks again!
