### ISSUE TITLE
Card without text

### ISSUE THREAD

**Issue by kenstone** [Savjee/button-text-card#27]
I know this repo is literally called button-text-card, but I'm interested in a button without any text. This would allow for some more versatility in this custom card, without having to load up a separate card for a plain styled button.

I'm happy to work on this; just wasn't sure if this was something that'd be worthwhile.

**Comment by Savjee** [comment]
This is already possible: 
![image](https://user-images.githubusercontent.com/817109/82866840-f7e9ed80-9f29-11ea-8898-1d4da237a89b.png)

```yaml
type: 'custom:button-text-card'
icon: "mdi:power-plug"
```

**Comment by kenstone** [comment]
Oh great! Could be another good example for the documentation. Not quite #26 but similar.
