### ISSUE TITLE
Haptic feedback mobile app

### ISSUE THREAD

**Issue by NOBvadder** [Savjee/button-text-card#28]
When I press the button in the android app I get a weird double vibration. 
Is it possible to turn it off for this button?

**Comment by Savjee** [comment]
That's interesting, do other UI elements of Lovelace have the same behavior?

**Comment by NOBvadder** [comment]
The standard button gives me a single vibration when pressed.
The custom button card has an option to set the type of the haptic feedback, but i get no vibration at all when i don't set that option.

**Comment by Savjee** [comment]
Closing this old issue for now.
Feel free to reopen when the issue is still present.
