### ISSUE TITLE
Lovelace theme not matching with card

### ISSUE THREAD

**Issue by Sirwa01** [Savjee/button-text-card#33]
Appreciatie the work done on this custom card! It looks much better then the default one.
But i can't figure out how to match the custom card with the theme i have setup (ios dark theme).
The area where the text it written, looks blank.

I am trying to match it within an horizantal stack configuration. Any idea what i am doing wrong? or is this option not yet written.

**thanks!**

![button-text-card](https://user-images.githubusercontent.com/68169397/97636423-62530c80-1a39-11eb-9dcb-d5e7ea52a8ab.PNG)

**Comment by Savjee** [comment]
Try making it a large card:

```yaml
large: true
```

**Comment by Sirwa01** [comment]
Thanks! i am currently using a different theme which looks nice with and without the **large:true** for the card! appreciate it!
