### ISSUE TITLE
Unable to correct use hide condition

### ISSUE THREAD

**Issue by chertvl** [Savjee/button-text-card#35]
Hi! Thanks for your module, its great.
Mostly im using it for notify me about some non-good states at my house, for example: bad temperature, unavailable sensors or dead batteries, moistures was on, etc.

Now I want to use this card for notify me to replace ground of my flower, I have a sensor that measure soil quality, it shows at 4-digit (most of time) number at the state (for example "2449" µS/cm)

When I try to add a card-notification with hide condition like is:
hide_condition: |
  [[[ return entity.state > "500" ]]]

this does not work, because I try to track 3-digit number, but the state is 4-digit now.
So what bug I have:
If state is 2350 (for examle) and I use THIS numbers for hide condition:
1  - card will shows
3  - card will hide
22 - card will show
24 - card will hide
234 - card will show
236 - card will hide
2349 - card will show
2351 - card will hide.

So how can I use state " >  500"  if module thinks the 500 is bigger then 2350, because it will compare only first 3 digits for 3-digit condition?

Thanks for any help.

P.s.: sorry for my english

**Comment by Savjee** [comment]
I'm not sure I understand the problem. But when you compare numbers in Javascript, you should not use quotes. Can you try if this works:

```yaml
hide_condition: |
    [[[ return entity.state > 500 ]]]
```

That will hide the card if the entity's state is higher than 500.

Be aware that you need to set an `entity` as well.

**Comment by chertvl** [comment]
Omg, you r right, its all quotes.
Now it works perfectly, many thanks and sorry.

**Comment by Savjee** [comment]
No worries ;)
