### ISSUE TITLE
Templating temperature

### ISSUE THREAD

**Issue by gio82c** [Savjee/button-text-card#36]
I am not very familiar with the codes, but I would like to display the optimal room temperature based on a temperature sensor, I used this formula, it works with all operands +, *, / but if I use the - what I need does not work , can someone help me?

`      [[[
        return 'Optimal Room Temperature: ' + states["sensor.temperature"].state - 5;
      ]]]`

**Comment by Savjee** [comment]
If I understand correctly, than this works:

```
[[[ return 'Optimal Room Temperature: ' + states["sensor.temperature"].state + 5; ]]]
```

But this does not?

```
[[[ return 'Optimal Room Temperature: ' + states["sensor.temperature"].state - 5; ]]]
```

That's weird. Can you make sure that "state" contains a number and not a string type?

**Comment by gio82c** [comment]
yes correct, the state is a temperature sensor so the result is for expample "28.1"

i try again and only work / or *
