### ISSUE TITLE
Custom element not found: button-text-card

### ISSUE THREAD

**Issue by Hohenloherin** [Savjee/button-text-card#43]
Configuration error detected:
Custom element not found: button-text-card

As a sudden or after updating to Home Assistant 2022.11.4 I get this error. I deleted the addon, reinstalled it and restarted HA. The error persists. What can I do?

My system runs on RPi4b: 
Home Assistant 2022.11.4
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by Savjee** [comment]
I'm also running the latest version, and the card works fine.

Can you share the full YAML configuration of the card you're making?

Also: make sure that button-text-card is included in the frontend.
Go to Settings > Dashboards > Three dots > Resources.
Makes sure your see something like this: `/hacsfiles/button-text-card/button-text-card.js?hacstag=241706284061`

**Comment by Hohenloherin** [comment]
What I see now, on my phone the card is shown correctly as always. The error only shows up on my computers. 

Button-text-card is included in frontend. 
This is the yaml:

`type: custom:button-text-card
entity: binary_sensor.endschalter_s
title: ACHTUNG Tor!
subtitle: Das Hoftor ist nicht komplett geschlossen.
icon: mdi:gate-alert
large: true
font_color: '#fff00'
background_color: '#ffff00'
hide_condition: |
  [[[ return entity.state === "on" ]]]`

**Comment by Hohenloherin** [comment]
Now it works again and I cannot say why!?

**Comment by Savjee** [comment]
Weird indeed!
