### ISSUE TITLE
Button Text Card failing to display anything in HA 2023.7

### ISSUE THREAD

**Issue by antfurn** [Savjee/button-text-card#49]
Hi, I'm seeing - or not seeing in ths case - an issue with your awesome Button Text Card.
When I updated to HA 2023.7, both cards I had setup stopped display anything at all. HA isn't giving me any obvious errors, just what is displayed in the screen shot.
I've updated the `button-text-card.js` to the lastest version from this repo (Apr 6th) and restarted HA but that didn't t fix it.
Previously I was on HA 2023.3

> Home Assistant 2023.7.1
> Frontend 20230705.1 - latest

![image](https://github.com/Savjee/button-text-card/assets/4171512/1d686383-1de1-483a-99ea-7716428cdf76)

**Comment by Savjee** [comment]
This was fixed, wasn't it?
I just forgot to reply to your issue.

**Comment by antfurn** [comment]
Yes 👍
