### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Dave-Parry** [Savjee/button-text-card#50]
I'm a newbie trying to install this but cant find the lovelace.config file.
Can you tell me where this is please?

**Comment by Savjee** [comment]
The card is available on HACS.
It's sort of a third-party App Store for Home Assistant: https://hacs.xyz/

**Comment by Dave-Parry** [comment]
Xavier,
Thanks for the reply.
I had installed it using hacs, but your instructions, item 4 said to add 
- url: /hacsfiles/button-text-card/button-text-card.js
 type: module
to the Lovelace config which I couldn’t find.
Also when I tried to add the card to my dashboard I couldn't find it. So I assumed the url was required.
But it's there now, so all good.

Regards
David Parry
***@***.***
