### ISSUE TITLE
HACS not working with link given in instructions

### ISSUE THREAD

**Issue by fitim7** [Savjee/button-text-card#8]
for Hacs the git@github.com:Savjee/button-text-card.git isn't working.

using the regular https://github.com/Savjee/button-text-card is working.

**Comment by Savjee** [comment]
I will update the README, thanks for notifying me!

This step won't be necessary in the near future. The plugin was added to HACS yesterday :)

**Comment by Savjee** [comment]
Fixed in 4b9d7b0754f3055b6b81e58a8c036a8f5bd34129
